using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Room surfaces by profile. Every material is an editable asset in
/// Resources/Surfaces, generated by FrontRoomsss → Rendering → Set up URP, post
/// and surfaces, and drawn with FrontRooms/Surface (world-projected, so wall
/// paper, carpet and the ceiling grid stay continuous across slabs).
/// Level 0 (Lobby, Shift, Exit): chevron paper, loop-pile carpet, 2'x4' tiles.
/// Level 4 (Office): painted drywall, 24" carpet tiles, 2'x2' tiles, louvers.
/// Level ! (Run): hospital corridor, white paint, VCT, red exit signs.
/// </summary>
public static class FrontRoomsSurfaces
{
    public enum Slot { Wall, Floor, Ceiling }

    static readonly Dictionary<string, Material> Cache = new Dictionary<string, Material>();
    static readonly HashSet<string> Missing = new HashSet<string>();

    public static Material Room(RoomRule rule, Slot slot)
    {
        switch (rule)
        {
            case RoomRule.Office: return Get(slot == Slot.Wall ? "Office_Wall" : slot == Slot.Floor ? "Office_Carpet" : "Office_Ceiling");
            case RoomRule.Run: return Get(slot == Slot.Wall ? "Run_Wall" : slot == Slot.Floor ? "Run_Floor" : "Run_Ceiling");
            case RoomRule.Exit: return Get(slot == Slot.Wall ? "Exit_Wallpaper" : slot == Slot.Floor ? "Exit_Carpet" : "L0_Ceiling");
            case RoomRule.Shift: return Get(slot == Slot.Wall ? "L0_Wallpaper_Shift" : slot == Slot.Floor ? "L0_Carpet_Shift" : "L0_Ceiling_Shift");
            default: return Get(slot == Slot.Wall ? "L0_Wallpaper" : slot == Slot.Floor ? "L0_Carpet" : "L0_Ceiling");
        }
    }

    /// <summary>Profile arrays in RoomRule order, the shape the room stream consumes.</summary>
    public static Material[] RoomArray(Slot slot)
    {
        var rules = (RoomRule[])System.Enum.GetValues(typeof(RoomRule));
        var result = new Material[rules.Length];
        for (var i = 0; i < rules.Length; i++) result[(int)rules[i]] = Room(rules[i], slot);
        return result;
    }

    public static Material DoorVeneer => Get("Door_Veneer");
    public static Material PaintedMetal => Get("Painted_Metal");
    public static Material TrofferLens => Get("Troffer_Lens");
    // The office reference and the film both show flat frosted (opal) lenses,
    // so Office fixtures share the Level 0 lens. OfficeLouver is kept for the
    // map's existing calls and now returns the frosted lens too.
    public static Material OfficeLens => Get("Troffer_Lens");
    public static Material OfficeLouver => OfficeLens;
    public static Material ParabolicLouver => Get("Office_Louver");
    public static Material ExitSign => Get("Run_ExitSign");
    public static Material CoveBase => Get("Cove_Base");
    public static Material CubicleFabric => Get("Office_Fabric");
    public static Material BlackedGlass => Get("Office_BlackedGlass");

    public static Material Get(string name)
    {
        if (Cache.TryGetValue(name, out var cached) && cached != null) return cached;
        var material = Resources.Load<Material>("Surfaces/" + name);
        if (material == null)
        {
            if (Missing.Add(name))
                Debug.LogWarning("[FrontRooms3D] Surface material '" + name + "' is missing. Run FrontRoomsss → Rendering → Set up URP, post and surfaces.");
            material = Lit("Missing / " + name, new Color(.55f, .52f, .45f), .2f);
        }
        Cache[name] = material;
        return material;
    }

    /// <summary>
    /// The project material Resources/Surfaces/&lt;name&gt;, or null without a
    /// warning (the prop kit falls back to the FBX's imported material).
    /// </summary>
    public static Material TryGet(string name)
    {
        if (string.IsNullOrEmpty(name)) return null;
        if (Cache.TryGetValue(name, out var cached) && cached != null) return cached;
        var material = Resources.Load<Material>("Surfaces/" + name);
        if (material != null) Cache[name] = material;
        return material;
    }

    /// <summary>
    /// A plain URP Lit material for props (desks, cabinets, the Relay). Cached
    /// by name so repeated props share one material.
    /// </summary>
    public static Material Lit(string name, Color color, float smoothness = .3f, float metallic = 0f, Color? emission = null)
    {
        if (Cache.TryGetValue(name, out var cached) && cached != null) return cached;
        var shader = Shader.Find("Universal Render Pipeline/Lit") ?? Shader.Find("Universal Render Pipeline/Simple Lit");
        var material = new Material(shader) { name = name };
        material.SetColor("_BaseColor", color);
        material.SetFloat("_Smoothness", smoothness);
        material.SetFloat("_Metallic", metallic);
        if (emission.HasValue)
        {
            material.EnableKeyword("_EMISSION");
            material.SetColor("_EmissionColor", emission.Value);
            material.globalIlluminationFlags = MaterialGlobalIlluminationFlags.RealtimeEmissive;
        }
        Cache[name] = material;
        return material;
    }
}
