#!/bin/sh
# Build the desktop Metal ray-traced glass bridge (G14) for Unity 6000.3.10f1, macOS arm64.
#
#   1. Embed FRGlassRTShared.h + FrontRoomsGlassRT.metal into build/FRGlassRTEmbedded.h (one MSL string).
#   2. Build and run tools/frglassrt_validate: it compiles that exact string with the OS Metal compiler,
#      creates every pipeline and runs the GPU layout self-test. Any shader error fails HERE, not in the game
#      (no offline Metal toolchain is needed; design 10 §1.9, decision D4).
#   3. Build Assets/Plugins/macOS/libFrontRoomsMetalGlassRT.dylib (arm64, macOS 13+, @rpath install name).
#
# Only run while no Unity process has this project open: the editor keeps a loaded dylib for its lifetime.
# Unity imports the dylib only for the Editor (macOS, ARM64) and Standalone macOS ARM64
# (Assets/Editor/RT/FrontRoomsGlassRTImporter.cs pins this); no other platform sees it.
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
UNITY_EDITOR_VERSION=${UNITY_EDITOR_VERSION:-6000.3.10f1}
UNITY_APP=${UNITY_APP:-/Applications/Unity/Hub/Editor/${UNITY_EDITOR_VERSION}/Unity.app}
PLUGIN_API="$UNITY_APP/Contents/PluginAPI"
OUTPUT_DIR="$PROJECT_ROOT/Assets/Plugins/macOS"
OUTPUT="$OUTPUT_DIR/libFrontRoomsMetalGlassRT.dylib"
BUILD_DIR="$SCRIPT_DIR/build"

if [ ! -f "$PLUGIN_API/IUnityGraphicsMetal.h" ]; then
  echo "Unity PluginAPI not found: $PLUGIN_API" >&2
  exit 1
fi
mkdir -p "$OUTPUT_DIR" "$BUILD_DIR"

# 1. embed the MSL (shared header first, then the kernels)
EMBED="$BUILD_DIR/FRGlassRTEmbedded.h"
{
  echo "// Generated by build_frontrooms_metal_glass_rt.sh from FRGlassRTShared.h + FrontRoomsGlassRT.metal. Do not edit."
  echo "#pragma once"
  echo 'static const char kFRGlassRTMSL[] = R"FRMSL('
  cat "$SCRIPT_DIR/FRGlassRTShared.h"
  cat "$SCRIPT_DIR/FrontRoomsGlassRT.metal"
  echo ')FRMSL";'
} > "$EMBED"

# 2. validate at build time
xcrun clang++ -std=c++17 -fobjc-arc -O1 -arch arm64 -mmacosx-version-min=13.0 \
  -I "$BUILD_DIR" -I "$SCRIPT_DIR" \
  -framework Metal -framework Foundation \
  -o "$BUILD_DIR/frglassrt_validate" "$SCRIPT_DIR/tools/frglassrt_validate.mm"
"$BUILD_DIR/frglassrt_validate"

# 3. the plugin
xcrun clang++ -std=c++17 -fobjc-arc -O2 -dynamiclib \
  -arch arm64 -mmacosx-version-min=13.0 \
  -Wall -Wno-unused-function -Wno-unguarded-availability-new \
  -install_name @rpath/libFrontRoomsMetalGlassRT.dylib \
  -isystem "$PLUGIN_API" -I "$BUILD_DIR" -I "$SCRIPT_DIR" \
  -framework Metal -framework Foundation \
  -o "$OUTPUT" "$SCRIPT_DIR/FrontRoomsMetalGlassRT.mm" "$SCRIPT_DIR/FRGlassRTScene.mm"

echo "Built $OUTPUT"
lipo -info "$OUTPUT"
otool -D "$OUTPUT" | tail -n 1
shasum "$OUTPUT"
