#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "FrontRoomsRuntimeMap.generated.h"

class UBoxComponent;
class UActorComponent;
class UDirectionalLightComponent;
class UExponentialHeightFogComponent;
class UPointLightComponent;
class UPostProcessComponent;
class USceneComponent;
class USkyLightComponent;
class UStaticMesh;
class UStaticMeshComponent;

/**
 * Runtime representation of the authored FrontRoomsLevel0 modules.
 *
 * The Unity map is generated at runtime and intentionally keeps its source
 * data in the migration contract.  This actor is the first UE presentation
 * layer: it builds four authored module shells on the 3 m grid, adds the
 * imported Unity props, and supplies the same collision and light landmarks
 * on every run.  It is deterministic and does not require a binary .umap,
 * which keeps the Windows-only migration usable from a clean checkout.
 */
UCLASS(BlueprintType)
class FRONTROOMS_API AFrontRoomsRuntimeMap : public AActor
{
    GENERATED_BODY()

public:
    AFrontRoomsRuntimeMap();

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FrontRooms|Map")
    int32 Seed = 20261001;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FrontRooms|Map")
    bool bGenerateOnBeginPlay = true;

    /** South-west world position of the player spawn, in centimetres. */
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "FrontRooms|Map")
    FVector PlayerSpawnLocation = FVector(150.0f, 150.0f, 105.0f);

    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "FrontRooms|Map")
    int32 GeneratedModuleCount = 0;

    /** Components generated by the deterministic construction pass. Keeping
     * the references lets an editor-saved .umap reopen with the same scene. */
    UPROPERTY(VisibleAnywhere, Instanced, Category = "FrontRooms|Map")
    TArray<TObjectPtr<UActorComponent>> GeneratedComponents;

    UFUNCTION(BlueprintCallable, Category = "FrontRooms|Map")
    void BuildMap();

protected:
    virtual void OnConstruction(const FTransform& Transform) override;
    virtual void BeginPlay() override;

private:
    UPROPERTY(VisibleAnywhere)
    TObjectPtr<USceneComponent> SceneRoot;

    bool bBuilt = false;

    void BuildModuleShell(const FName& ModuleName, const FVector& Origin, const FVector2D& SizeMeters,
        float CeilingMeters, bool bOffice, bool bTall);
    void AddBox(const FName& Name, const FVector& RelativeLocation, const FVector& SizeCm,
        bool bCollision = true);
    void AddPointLight(const FName& Name, const FVector& RelativeLocation, const FLinearColor& Color,
        float Intensity, float AttenuationRadius);
    void AddProp(const FString& AssetPath, const FName& Name, const FVector& RelativeLocation,
        float YawDegrees = 0.0f, const FVector& Scale = FVector(1.0f));
    UStaticMesh* LoadMesh(const FString& AssetPath) const;
};
