# Per-sheet editorial data for the interactables K-sheets (titles, ledes, era).
# Sources: 10_spec.md (sections cited per entry), 02_period_hardware.md, 06_period_windows.md.
# chip vocabulary = 平面视觉's: "Current stock" | "Second-hand" | "Timeless".

SHEETS = [
    # ---------------------------------------------------------------- doors
    dict(id="doorframe_wood", family="Doors · frames", title="Wood door frame",
         kits=["Kit_DoorFrame_Wood"],
         lede="Walnut ranch casing, applied wood stop and an oak saddle: the Lobby's older office doorway.",
         span=[1955, 1990], chip="Second-hand",
         era="Wood-cased openings with stain-grade casing are the older office fit-out (02 §2.2; film F09 'dark frame'). Ranch casing and back band, no plinth blocks (none in 1990 commercial work).",
         members=["L0-F"], src=["10_spec §2.3", "02 §2.2"]),
    dict(id="doorframe_steel", family="Doors · frames", title="Steel door frame",
         kits=["Kit_DoorFrame_Steel", "Kit_DoorFrame_Steel_Alu"],
         lede="Pressed 16-gauge steel in dark bronze with a formed 16 mm stop and three rubber silencers.",
         span=[1955, 2000], chip="Timeless",
         era="The SDI hollow-metal frame: 2 in face, 5/8 in stop, 16 ga interior (SDI 111A). The form is unchanged from well before 1990. The _Alu variant gives the Exit its clear-anodised look.",
         members=["L0-K", "OF-F", "OF-K", "RN-F", "RN-K", "EX-F (Alu)", "EX-K (Alu)"], src=["10_spec §2.3", "02 §2.2"]),
    dict(id="doorleaf_veneer", family="Doors · leaves", title="Veneer door",
         kits=["Kit_DoorLeaf_Veneer", "Kit_DoorLeaf_Veneer_Oak"],
         lede="Flush 1-3/4 in veneer leaf with hardwood edge bands. No keyhole: a free door reads warm and dark.",
         span=[1955, 2000], chip="Timeless",
         era="The flush stain-grade veneer door with a brass lever is the project's own film still F09 and IP canon. Oak variant (chrome butts) for the Office and Exit.",
         members=["L0-F", "OF-F (Oak)", "EX-F (Oak)"], src=["10_spec §2.3", "02 §1, §2.1"]),
    dict(id="doorleaf_steel", family="Doors · leaves", title="Steel door",
         kits=["Kit_DoorLeaf_Steel", "Kit_DoorLeaf_Steel_PaintedMetal"],
         lede="Flush hollow-metal leaf in almond enamel with stainless kick plates: the locked door reads pale from 20 m.",
         span=[1955, 2000], chip="Timeless",
         era="Back-of-house rooms had painted hollow-metal doors (SDI 108 Level 2 for storage and utility). Almond enamel needs the new Door_Enamel surface (P-4); _PaintedMetal is the spec's working fallback.",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §2.1, §2.3", "02 §2.1", "05 §6.2"]),
    dict(id="doorleaf_steellite", family="Doors · leaves", title="Steel door with lite",
         kits=["Kit_DoorLeaf_SteelLite"],
         lede="The steel leaf with a 4 x 25 in vision lite at 1.575 m: Red's see-through option for the Run.",
         span=[1955, 1992], chip="Timeless",
         era="Narrow vision lites sit 60-66 in up (02 §4.3). Wired glass was the fire-door glazing until US production stopped in 1992; the wired look needs Glass_Wired from the glass track.",
         members=["RN-K (option)"], src=["10_spec §2.3", "02 §6.1", "06 §2.4"]),
    dict(id="doorleaf_ward", family="Doors · leaves", title="Ward door",
         kits=["Kit_DoorLeaf_Ward"],
         lede="Wood-grain laminate with a stainless armor plate, push plate and offset D-pull: push and pull, no latch.",
         span=[1975, 2000], chip="Current stock",
         era="A hospital-corridor door: laminate face, armor plate to 34 in on the push face, kick plate on the pull face. No latch, rose or strike.",
         members=["RN-F"], src=["10_spec §2.3", "04 §5.3"]),
    dict(id="door_closer", family="Doors · hardware", title="Surface closer",
         kits=["Kit_DoorCloser_Body", "Kit_DoorCloser_Arm", "Kit_DoorCloser_Forearm", "Kit_DoorCloser_Shoe"],
         lede="A regular-arm surface closer on the pull face, two links to a shoe on the head. Possible only because doors now swing one way.",
         span=[1958, 2000], chip="Timeless",
         era="Surface closers were standard on commercial doors; the heavy-duty LCN 4010/4110 series dates from 1958. Arm lengths come from the linkage solve (ESTIMATE, to check against a 4010 template).",
         members=["OF-F", "OF-K", "RN-F", "RN-K", "EX-F", "EX-K"], src=["10_spec §2.4", "02 §5.3"],
         parts=True),
    dict(id="exit_crossbar", family="Doors · hardware", title="Exit crossbar",
         kits=["Kit_ExitDevice_Crossbar"],
         lede="A rim crossbar exit device across the push face: the true Exit opens with a push.",
         span=[1950, 1995], chip="Second-hand",
         era="Tube crossbars on two end cases are the older exit-device form; touch-bar devices were taking over by 1990 (era note 'push bars on exits').",
         members=["EX-F"], src=["10_spec §2.4"]),
    dict(id="door_sign", family="Doors · signage", title="Door sign",
         kits=["Kit_DoorSign"],
         lede="Two-ply engraved plate, ivory letters on dark brown at 60 in: EMPLOYEES ONLY, no Braille.",
         span=[1970, 1991], chip="Current stock",
         era="Engraved two-colour room signs at 60 in to centre (UFAS 1984 / ADAAG 1991). No Braille: the ADAAG requirement post-dates 1990. The lettering needs the Prop_SignEngraved atlas (P-4); until then the face renders as a blank light grey-brown preview (#796961), not the dark brown target.",
         members=["L0-K", "OF-K", "RN-K (STAFF ONLY)"], src=["10_spec §2.4", "05 §6.2", "02 §4.3"]),
    dict(id="door_numberplate", family="Doors · signage", title="Zone number plate",
         kits=["Kit_DoorNumberPlate", "Kit_DoorNumberPlate_Blue", "Kit_DoorNumberPlate_White"],
         lede="An engraved plate beside the keyhole in the key tag's colour: the door shows the number of its key.",
         span=[1970, 2000], chip="Timeless",
         era="A facility key system indexes keys by room code, so tag code = door code is the period system (02 §8.2). Digits come from the Prop_KeyTagNo atlas (P-4).",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §2.4", "02 §8.2"]),
    dict(id="exit_sign", family="Doors · signage", title="Exit sign",
         kits=["Kit_ExitSign", "Kit_ExitSign_Dead"],
         lede="Stamped-steel EXIT sign with 6 in stencil letters over the push face; the dead variant is unlit.",
         span=[1970, 1995], chip="Current stock",
         era="A 1990 stamped-steel wall exit sign, emissive face only (no Light). Run_ExitSign_Dead is a new material (P-4); red or green letters is Red's call.",
         members=["EX-F (lit)", "EX-K (dead)"], src=["10_spec §2.4"]),
    # ---------------------------------------------------------------- lock
    dict(id="lock_escutcheon", family="Lock · mortise set", title="Escutcheon",
         kits=["Kit_Lock_Escutcheon", "Kit_Lock_Escutcheon_Brass"],
         lede="A tall satin-chrome plate: knob below, IC cylinder above. Plate plus dot reads as locked at 2-5 m.",
         span=[1955, 2000], chip="Timeless",
         era="Mortise locks stayed 'widely installed in industrial, commercial, and institutional environments' (02 §4.4). US26D satin chrome; locked hardware stays chrome in every level.",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1", "02 §4.4, §10"]),
    dict(id="lock_cylinder", family="Lock · mortise set", title="IC cylinder",
         kits=["Kit_Lock_CylinderShell", "Kit_Lock_CylinderShell_Brass"],
         lede="An interchangeable-core figure-8 face, no brand: the keyhole the key shot frames.",
         span=[1925, 2000], chip="Timeless",
         era="IC cores (Best type) since the 1920s. Core dimensions are an ESTIMATE, unverified against a real SFIC.",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1", "02 §13"]),
    dict(id="lock_plug", family="Lock · mortise set", title="Plug",
         kits=["Kit_Lock_Plug"],
         lede="The plug with an open keyway and six pin tips. It turns 90 degrees with the key, then back.",
         span=[1925, 2000], chip="Timeless",
         era="US pins-up: the key goes in cuts uppermost (02 §4.2, forum-grade). One keyway profile is shared by the key and the plug (10 §3.2).",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1, §3.2"]),
    dict(id="lock_knob", family="Lock · mortise set", title="Knurled knob",
         kits=["Kit_Lock_Knob", "Kit_Lock_Knob_Brass"],
         lede="A 54 mm ball knob with a knurled band, the 1984 touch mark for doors to hazardous rooms.",
         span=[1984, 1993], chip="Current stock",
         era="UFAS 1984 §4.29.3: a textured, e.g. knurled, knob marks doors to hazardous areas. Knobs still outsold levers 80:20 in the early 1990s; service doors kept them.",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1", "02 §3.1, §3.2"]),
    dict(id="lock_deadbolt", family="Lock · mortise set", title="Deadbolt",
         kits=["Kit_Lock_Deadbolt"],
         lede="A 25 mm deadbolt with two hardened-insert dots. The key throws it; it is what locks the door.",
         span=[1955, 2000], chip="Timeless",
         era="Commercial deadbolts throw 1 in (02 §4.2). Keyed both faces is a game liberty: the key works from the side the player stands on.",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1", "02 §4.2"]),
    dict(id="lock_latch_mortise", family="Lock · mortise set", title="Mortise latchbolt",
         kits=["Kit_Lock_Latchbolt_Mortise"],
         lede="Deadlocking latchbolt, 19 mm throw, 30 degree bevel, with the auxiliary plunger beside it.",
         span=[1955, 2000], chip="Timeless",
         era="A passage-function latch: either knob retracts it, the deadbolt does the locking (10 §3.1).",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1"]),
    dict(id="lock_strike_mortise", family="Lock · mortise set", title="Mortise strike",
         kits=["Kit_Lock_StrikeMortise"],
         lede="Curved-lip strike with latch and deadbolt openings and dust boxes. It tears off when the Relay breaks the door.",
         span=[1955, 2000], chip="Timeless",
         era="Strike in the lock's finish on the latch jamb, a separate render-only part so it can detach (audit §3.7).",
         members=["L0-K", "OF-K", "RN-K", "EX-K"], src=["10_spec §3.1", "02 §5.2"]),
    dict(id="lock_rose", family="Lock · bored set", title="Rose",
         kits=["Kit_Lock_Rose", "Kit_Lock_Rose_Brass"],
         lede="A 70 mm stepped rose under the lever: brass on the Lobby door, satin chrome elsewhere.",
         span=[1980, 2000], chip="Current stock",
         era="Cylindrical (bored) locksets are the most common commercial lock (02 §4.1). Brass US3/US4 for the Lobby's free door, US26D chrome for the rest; chrome against brass is a 2-5 m cue.",
         members=["L0-F (brass)", "OF-F", "EX-F"], src=["10_spec §3.1", "02 §4.1, §10"]),
    dict(id="lock_lever", family="Lock · bored set", title="Lever",
         kits=["Kit_Lock_Lever", "Kit_Lock_Lever_Brass"],
         lede="A 121 mm commercial lever, 64 mm proud: free doors had the accessible handle a decade before the ADA.",
         span=[1980, 2000], chip="Current stock",
         era="Levers were the accessible standard from ANSI A117.1-1980 and UFAS 1984; the ADA required them only for buildings occupied after 26 Jan 1993 (02 §3.1).",
         members=["L0-F (brass)", "OF-F", "EX-F (S face)"], src=["10_spec §3.1", "02 §3.1, §4.1"]),
    dict(id="lock_latch_bored", family="Lock · bored set", title="Bored latchbolt",
         kits=["Kit_Lock_Latchbolt_Bored", "Kit_Lock_Latchbolt_Bored_Brass"],
         lede="A 1/2 in throw latch with deadlatch plunger. The lever's 35 degrees pulls it in.",
         span=[1955, 2000], chip="Timeless",
         era="1/2 in latch throw, 1-1/8 x 2-1/4 in faceplate (D Series pattern, 02 §4.1).",
         members=["L0-F (brass)", "OF-F", "EX-F"], src=["10_spec §3.1", "02 §4.1"]),
    dict(id="lock_strike_bored", family="Lock · bored set", title="Bored strike",
         kits=["Kit_Lock_StrikeBored", "Kit_Lock_StrikeBored_Brass"],
         lede="The ANSI 4-7/8 in curved-lip strike with one opening and a dust box.",
         span=[1955, 2000], chip="Timeless",
         era="ANSI curved-lip strike 1-1/4 x 4-7/8 in (02 §5.2).",
         members=["L0-F (brass)", "OF-F", "EX-F"], src=["10_spec §3.1", "02 §5.2"]),
    # ---------------------------------------------------------------- keys
    dict(id="key_zone", family="Keys", title="Zone key",
         kits=["Kit_Key_Zone", "Kit_Key_Zone_Nickel"],
         lede="A 58 mm cut brass duplicate, six cuts, a generic paddle bow. Nickel is the factory original.",
         span=[1955, 2000], chip="Timeless",
         era="Factory keys were nickel silver ('two nickel silver keys per lock'); brass duplicates are the hardware-store copy, and brass reads under yellow light (02 §8.1). No maker's bow, no stamping in v1.",
         members=["every zone key"], src=["10_spec §3.3", "02 §8.1"]),
    dict(id="key_ring", family="Keys", title="Split ring",
         kits=["Kit_KeyRing"],
         lede="A flat-wire split ring, two turns, 25 mm: the key and the tag hang from it.",
         span=[1950, 2000], chip="Timeless",
         era="Flat steel double coil, nickel-plated, Ø 25-32 mm (02 §8.2).",
         members=["every zone key"], src=["10_spec §4.1", "02 §8.2"]),
    dict(id="key_tag_rect", family="Keys · tags", title="Key tag, square",
         kits=["Kit_KeyTag_Rect", "Kit_KeyTag_Rect_Blue", "Kit_KeyTag_Rect_White"],
         lede="A plastic tag with a paper insert and a typed number: shape and colour name the zone.",
         span=[1961, 2000], chip="Timeless",
         era="Coloured plastic ID tags with a label window (Lucky Line, family owned since 1961; 02 §8.2). 3 shapes x red, blue, white = 9 identities. Numbers in Courier Prime need Prop_KeyTagNo (P-4).",
         members=["zone keys"], src=["10_spec §4.1", "02 §8.2", "03 §2.5"]),
    dict(id="key_tag_round", family="Keys · tags", title="Key tag, round",
         kits=["Kit_KeyTag_Round", "Kit_KeyTag_Round_Blue", "Kit_KeyTag_Round_White"],
         lede="A 38 mm round tag with a 26 mm window, the second shape of the zone code.",
         span=[1961, 2000], chip="Timeless",
         era="As the square tag (02 §8.2). The number insert is one quad on Prop_KeyTagNo.",
         members=["zone keys"], src=["10_spec §4.1", "02 §8.2"]),
    dict(id="key_tag_long", family="Keys · tags", title="Key tag, valet",
         kits=["Kit_KeyTag_Long", "Kit_KeyTag_Long_Blue", "Kit_KeyTag_Long_White"],
         lede="A 76 mm valet tag, the long third shape of the zone code.",
         span=[1961, 2000], chip="Timeless",
         era="As the square tag (02 §8.2).",
         members=["zone keys"], src=["10_spec §4.1", "02 §8.2"]),
    dict(id="key_board", family="Keys · hosts", title="Key board",
         kits=["Kit_KeyHookBoard"],
         lede="A dark painted board with eight brass cup hooks and paper number strips: the Lobby's key host.",
         span=[1950, 2000], chip="Timeless",
         era="Hook boards with cup hooks in a grid were the everyday facility key store (02 §9, 03 §2.3). Spec name Kit_KeyBoard; shipped as Kit_KeyHookBoard because Kit_KeyBoard and Kit_Keyboard are one file on this Mac.",
         members=["Lobby"], src=["10_spec §4.2", "02 §9", "build_g3"]),
    dict(id="key_cabinet", family="Keys · hosts", title="Key cabinet",
         kits=["Kit_KeyCabinet"],
         lede="An almond steel wall cabinet with 24 hooks and an index card, its door swung flat to the wall.",
         span=[1950, 2000], chip="Timeless",
         era="Telkee-type institution key cabinets (trademark filed 1928), no brand (02 §9). The Office's key host.",
         members=["Office"], src=["10_spec §4.2", "02 §9"]),
    dict(id="key_hook", family="Keys · hosts", title="Key hook",
         kits=["Kit_KeyHook"],
         lede="One brass cup hook in the wall, at 1.476 m: the procedural rooms' fallback host.",
         span=[1950, 2000], chip="Timeless",
         era="A single key on a hook by a door (02 §9). At most one key in four, red or blue tag only (10 §4.2).",
         members=["any room"], src=["10_spec §4.2, §4.3", "02 §9"]),
    # ---------------------------------------------------------------- windows
    dict(id="window_wood", family="Windows", title="Wood window",
         kits=["Kit_WindowFrame_Wood"],
         lede="A walnut back-office light with casing, horned stool and apron: older stock in the Lobby.",
         span=[1955, 1985], chip="Second-hand",
         era="Wood borrowed lights with stool, apron and casing belong to older buildings (NPS ITS 31's 'mahogany trim around openings'; 06 §2.1). Same casing profile as the wood door frame.",
         members=["W-L0"], src=["10_spec §5.1", "06 §2.1, §3.1"]),
    dict(id="window_steel", family="Windows", title="Steel window",
         kits=["Kit_WindowFrame_Steel", "Kit_WindowFrame_Steel_Enamel"],
         lede="An SDI borrowed-light frame in bronze, 30 oval-head screws on the room-side stop.",
         span=[1955, 2000], chip="Timeless",
         era="Pressed-steel borrowed-light frames: integral stop on the hall side, screwed removable stop on the room side at <= 9 in centres (SDI 111A; UH spec; 06 §2.2). The _Enamel variant is the Run's corridor light (Door_Enamel, P-4).",
         members=["W-OF", "W-RN (Enamel)"], src=["10_spec §5.1", "06 §2.2, §3.2, §3.3"]),
    dict(id="window_alu", family="Windows", title="Aluminium window",
         kits=["Kit_WindowFrame_Alu"],
         lede="A clear-anodised aluminium office front with bevelled snap-in beads and a black vinyl gasket.",
         span=[1982, 2000], chip="Current stock",
         era="Demountable aluminium partition glazing, US Gypsum patents US4463535 / US4443984 (filed 1981-82, granted 1984). Clear and bronze anodising were both ordinary by 1990 (06 §2.3).",
         members=["W-EX"], src=["10_spec §5.1", "06 §2.1, §2.3"]),
    dict(id="miniblind_raised", family="Windows", title="Mini-blind, raised",
         kits=["Kit_MiniBlind_Raised"],
         lede="A 1-inch aluminium mini-blind, raised clear of the opening, almond slats.",
         span=[1975, 2000], chip="Current stock",
         era="Mini-blinds were 70-80 % of the US window-covering market in 1981; the 1993 Sears catalogue sells Levolor 1-inch blinds in Almond (06 §2.5). Optional on Office windows by edge hash.",
         members=["W-OF (option)"], src=["10_spec §5.1", "06 §2.5"]),
    dict(id="miniblind_lowered", family="Windows", title="Mini-blind, lowered",
         kits=["Kit_MiniBlind_Lowered"],
         lede="The same blind 2.40 m wide, lowered and half-tilted: decor for the dark interior window only.",
         span=[1975, 2000], chip="Current stock",
         era="As the raised blind. Never on a breakable map window: it would hang in the climb opening (10 §5.1 rules).",
         members=["Kit_InteriorWindow (G5)"], src=["10_spec §5.1", "06 §2.5"]),
    # ---------------------------------------------------------------- existing, unchanged
    dict(id="doorway_studs", family="Doors · existing", title="Stud doorway",
         kits=["Kit_DoorwayStuds", "Kit_DoorwayStuds140", "Kit_DoorwayStuds180"],
         lede="Raw 2x4 opening outlined in blue painter's tape, a 3M product from 1988.",
         span=[1950, 2000], chip="Timeless",
         era="Unchanged since the 2026-10-02 sheets: the FBX files match the real project byte for byte. Already on K45 (2328:1258); re-rendered here only for completeness.",
         members=["renovation rooms"], src=["K45"], existing="K45 · Stud doorway (2328:1258)"),
]

LABELS = {
    "Prop_SteelBrown": "Brown steel", "Prop_Rubber": "Rubber", "Prop_Chrome": "Chrome",
    "Prop_Aluminium": "Aluminium", "Prop_WoodWalnut": "Walnut", "Prop_WoodOak": "Golden oak",
    "Prop_Brass": "Brass", "Door_Enamel": "Almond enamel", "Prop_Glass": "Glass",
    "Painted_Metal": "Painted metal", "Door_Veneer": "Door veneer", "Prop_WoodLaminate": "Wood laminate",
    "Prop_PlasticRed": "Red plastic", "Prop_PlasticBlue": "Blue plastic", "Prop_PlasticWhite": "White plastic",
    "Prop_PlasticBlack": "Black plastic", "Prop_KeyTagNo": "Typed numbers", "Prop_SignEngraved": "Engraved sign",
    "Prop_Studs": "Spruce studs", "Prop_TapeBlue": "Painter's tape", "Prop_SteelBlack": "Black steel",
    "Run_ExitSign": "Lit EXIT face", "Run_ExitSign_Dead": "Dead EXIT face", "Prop_SteelAlmond": "Almond steel",
    "Prop_WoodDark": "Dark wood",
}

# Existing K-sheet swatches (read from PROP KIT 2324:852, 2026-10-03): reuse the exact hex so sheets agree.
EXISTING_HEX = {
    "Prop_SteelBrown": "#3b2e25", "Prop_Rubber": "#050505", "Prop_Chrome": "#d8d8d8", "Prop_Aluminium": "#b8b8b4",
    "Prop_WoodWalnut": "#4a3020", "Prop_WoodOak": "#9a6a3a", "Prop_Brass": "#b08a4a", "Prop_Glass": "#d1e0e0",
    "Prop_PlasticRed": "#8c0f0d", "Prop_PlasticWhite": "#d9d5c8", "Prop_PlasticBlack": "#1a1a1a",
    "Prop_WoodDark": "#2d1c14", "Prop_SteelBlack": "#1e1e1e", "Prop_Studs": "#c9ae83", "Prop_TapeBlue": "#2e86c1",
}

# Slots with no Unity surface yet (10_spec §8 P-4): Unity renders the FBX's own preview material.
P4 = {"Door_Enamel", "Prop_KeyTagNo", "Prop_SignEngraved", "Run_ExitSign_Dead"}
